// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACWsuKxExAozyjhoG_OAW6oGXXIZvUCgE',
    appId: '1:262442832360:web:90be5a627b7827c95cd45d',
    messagingSenderId: '262442832360',
    projectId: 'inventory-management-app-5e9db',
    authDomain: 'inventory-management-app-5e9db.firebaseapp.com',
    databaseURL: 'https://inventory-management-app-5e9db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-management-app-5e9db.firebasestorage.app',
    measurementId: 'G-LYC5KVSTTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-MMeAAjjOKNJ3Z0_qhFnOITOZXOjb5Q',
    appId: '1:262442832360:android:5b68a14c8c711bee5cd45d',
    messagingSenderId: '262442832360',
    projectId: 'inventory-management-app-5e9db',
    databaseURL: 'https://inventory-management-app-5e9db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-management-app-5e9db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq9FsEGSWr1mTEJI53GQ4A9qPsAIxHInw',
    appId: '1:262442832360:ios:551272316b10aa835cd45d',
    messagingSenderId: '262442832360',
    projectId: 'inventory-management-app-5e9db',
    databaseURL: 'https://inventory-management-app-5e9db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-management-app-5e9db.firebasestorage.app',
    iosBundleId: 'com.rkatsiari.inventory.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq9FsEGSWr1mTEJI53GQ4A9qPsAIxHInw',
    appId: '1:262442832360:ios:551272316b10aa835cd45d',
    messagingSenderId: '262442832360',
    projectId: 'inventory-management-app-5e9db',
    databaseURL: 'https://inventory-management-app-5e9db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-management-app-5e9db.firebasestorage.app',
    iosBundleId: 'com.rkatsiari.inventory.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACWsuKxExAozyjhoG_OAW6oGXXIZvUCgE',
    appId: '1:262442832360:web:5f6db6b3d05dbdff5cd45d',
    messagingSenderId: '262442832360',
    projectId: 'inventory-management-app-5e9db',
    authDomain: 'inventory-management-app-5e9db.firebaseapp.com',
    databaseURL: 'https://inventory-management-app-5e9db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventory-management-app-5e9db.firebasestorage.app',
    measurementId: 'G-FF4M76J3QY',
  );
}
